### ISSUE TITLE
Fails to startup in Create 2022.3.1

### ISSUE THREAD

**Issue by cauberthonda** [Vadim-Karpenko/omniverse-material-manager-extended#1]
Removing import omni.kit.viewport_legacy in extensions.py did the trick for me.

**Comment by Vadim-Karpenko** [comment]
Fixed with https://github.com/Vadim-Karpenko/omniverse-material-manager-extended/commit/8aed31ebe3465762331aed6a3c2131b4ea028d6c, thank you for letting me know about this issue!
